name: peerdart
version: 0.5.5
homepage: https://github.com/MuhammedKpln/peerdart
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/MuhammedKpln/peerdart
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  uuid: ^4.1.0
  flutter_webrtc: ^0.12.3
  web_socket_channel: ^3.0.1
  events_emitter: ^0.5.2
dev_dependencies:
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
